---
name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: test
        uses: a-light-win/builder@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          go_project: "."
